name: Sync Fork (Basic)

on:
  schedule:
    - cron: '0 * * * *'   # hourly (UTC)
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    env:
      SYNC_TOKEN: ${{ secrets.SYNC_TOKEN }}

    steps:
      - name: Checkout main (with PAT)
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          token: ${{ env.SYNC_TOKEN }}

      - name: Configure git & auth
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # ensure pushes use the PAT
          git remote set-url origin https://x-access-token:${SYNC_TOKEN}@github.com/${{ github.repository }}.git

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/CoplayDev/unity-mcp.git || true
          git fetch upstream main

      - name: Merge upstream/main into main (FF if possible)
        run: |
          git checkout -B main
          # try fast-forward first; if not possible, do a regular merge
          if ! git merge --ff-only upstream/main; then
            git merge --no-edit upstream/main
          fi

      - name: Push back to fork
        run: |
          git push origin main
