name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/CoplayDev/unity-mcp.git || true
          git fetch upstream main

      - name: Show state (debug)
        run: |
          echo "GITHUB_REF_NAME=$GITHUB_REF_NAME"
          git remote -v
          git status
          git log --oneline --graph --decorate -n 10

      - name: Fast-forward if possible
        id: ff
        run: |
          set -e
          # Ensure we are on a branch
          git checkout -B main
          # Check if anything to update
          if [ "$(git rev-list --count HEAD..upstream/main)" -eq 0 ]; then
            echo "changed=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          # Try fast-forward only (no merge commits)
          if git merge --ff-only upstream/main; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=pr" >> $GITHUB_OUTPUT
          fi

      - name: Push fast-forward
        if: steps.ff.outputs.changed == 'true'
        run: |
          git push origin main

      - name: Create PR instead (branch protection or conflicts)
        if: steps.ff.outputs.changed == 'pr'
        uses: peter-evans/create-pull-request@v6
        with:
          branch: sync/upstream-main
          title: "Sync: upstream/main → main"
          body: "Automated sync from upstream."
          commit-message: "Sync fork with upstream"
          base: main
          delete-branch: true
