name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/CoplayDev/unity-mcp.git || true
          git fetch upstream main

      - name: Debug state
        run: |
          echo "Current branch: $(git symbolic-ref --short HEAD || echo '<detached>')"
          echo "Our HEAD: $(git rev-parse --short HEAD)"
          echo "Upstream main: $(git rev-parse --short upstream/main)"
          echo "Ahead count (us..upstream): $(git rev-list --count HEAD..upstream/main)"
          git log --oneline --graph --decorate -n 10

      - name: Decide if behind
        id: behind
        run: |
          AHEAD=$(git rev-list --count HEAD..upstream/main)
          if [ "$AHEAD" -gt 0 ]; then
            echo "behind=true" >> $GITHUB_OUTPUT
          else
            echo "behind=false" >> $GITHUB_OUTPUT
          fi

      - name: Fast-forward (no merge commit)
        id: ff
        if: steps.behind.outputs.behind == 'true'
        run: |
          set -e
          git checkout -B main
          if git merge --ff-only upstream/main; then
            echo "mode=push" >> $GITHUB_OUTPUT
          else
            echo "mode=pr" >> $GITHUB_OUTPUT
          fi

      - name: Push fast-forward
        if: steps.ff.outputs.mode == 'push'
        run: |
          git push origin main
          echo "Pushed FF update to origin/main"

      - name: Create PR (cannot FF or push blocked)
        if: steps.ff.outputs.mode == 'pr'
        uses: peter-evans/create-pull-request@v6
        with:
          branch: sync/upstream-main
          title: "Sync: upstream/main → main"
          body: "Automated sync from upstream. FF not possible (or push blocked by rules)."
          commit-message: "Sync fork with upstream"
          base: main
          delete-branch: true
